#command: docker-compose up -d

version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_USER: root
      MYSQL_PASSWORD: mypass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_USER: root
      MYSQL_PASSWORD: mypass
    ports:
      - '3308:80'
volumes:
  db_data:
